### ISSUE TITLE
gdb 7.8.2 doesn't build with python 3.7

### ISSUE THREAD

**Issue by dciabrin** [dciabrin/ngdevkit-toolchain#3]
When the default python resolves to python 3.7 (e.g. in fedora 32), building the toolchain fails due to gdb 7.8.2 not compatible with python 3.7:

```
/home/dciabrin/dam/ngdk/ngdevkit-toolchain/toolchain/gdb-7.8.2/gdb/python/python.c: In function ‘_initialize_python’:
/home/dciabrin/dam/ngdk/ngdevkit-toolchain/toolchain/gdb-7.8.2/gdb/python/python.c:1691:3: error: too few arguments to function ‘_PyImport_FixupBuiltin’
 1691 |   _PyImport_FixupBuiltin (gdb_module, "_gdb");
      |   ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.7m/Python.h:145,
                 from /home/dciabrin/dam/ngdk/ngdevkit-toolchain/toolchain/gdb-7.8.2/gdb/python/python-internal.h:97,
                 from /home/dciabrin/dam/ngdk/ngdevkit-toolchain/toolchain/gdb-7.8.2/gdb/python/python.c:94:
/usr/include/python3.7m/import.h:112:17: note: declared here
  112 | PyAPI_FUNC(int) _PyImport_FixupBuiltin(
      |                 ^~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:2369: python.o] Error 1
make[3]: Leaving directory '/home/dciabrin/dam/ngdk/ngdevkit-toolchain/build/nggdb/gdb'
make[2]: *** [Makefile:8668: all-gdb] Error 2
make[2]: Leaving directory '/home/dciabrin/dam/ngdk/ngdevkit-toolchain/build/nggdb'
make[1]: *** [Makefile:832: all] Error 2
```
